export const pizza1 = [
    {
        id: 843,
        competency: 3000,
        flowingTimes: 5,
        giftName: 'Redmi 13C 5G',
        img_url: require('./img/mi1.png'),
        jackpot: 3000,
    },
    {
        id: 844,
        competency: 3200,
        flowingTimes: 5,
        giftName: 'Redmi 13C',
        img_url: require('./img/mi2.png'),
        jackpot: 3200,
    },
    {
        id: 845,
        competency: 5999,
        flowingTimes: 5,
        giftName: 'Xiaomi 14',
        img_url: require('./img/mi3.png'),
        jackpot: 5999,
    },
    {
        id: 846,
        competency: 8999,
        flowingTimes: 5,
        giftName: 'Xiaomi 14 Ultra',
        img_url: require('./img/mi4.png'),
        jackpot: 8999,
    },
    {
        id: 847,
        competency: 3299,
        flowingTimes: 5,
        giftName: 'Xiaomi 13T',
        img_url: require('./img/mi5.png'),
        jackpot: 3299,
    },
    {
        id: 848,
        competency: 2499,
        flowingTimes: 5,
        giftName: 'Redmi Note 13 Pro 5G',
        img_url: require('./img/mi6.png'),
        jackpot: 2499,
    },
    {
        id: 849,
        competency: 1999,
        flowingTimes: 5,
        giftName: 'Redmi Note 13 5G',
        img_url: require('./img/mi7.png'),
        jackpot: 1999,
    },
];
export const pizza2 = [
    {
        id: 850,
        competency: 1499,
        flowingTimes: 5,
        giftName: 'Redmi Note 13',
        img_url: require('./img/mi8.png'),
        jackpot: 1499,
    },
    {
        id: 851,
        competency: 599,
        flowingTimes: 5,
        giftName: 'Redmi A3',
        img_url: require('./img/mi9.png'),
        jackpot: 599,
    },
];
